[project]
name = "weeklyreporttools"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "customtkinter>=5.2.2",
    "openpyxl>=3.1.5",
    "packaging>=26.0",
]
